import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import * as fs from "node:fs";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

const pluginRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const syncScriptPath = join(pluginRoot, "skill-aliases", "sync-rules", "scripts", "sync-agent-rules.mjs");

test("#given a master AGENTS.md rule file #when sync-agent-rules is run #then compiles and copies rules to all platforms", async () => {
  // 1. Setup mock environment
  const testDir = join(pluginRoot, "test-sync-sandbox");
  if (!fs.existsSync(testDir)) {
    fs.mkdirSync(testDir);
  }

  const masterPath = join(testDir, "AGENTS.md");
  const dummyRules = `# Dummy Agent Rules

Rule 1: Always use clean architecture.
<!-- IF CURSOR -->
Rule 2: Enforce typescript strict types for Cursor.
<!-- ENDIF -->
<!-- IF CLAUDE -->
Rule 3: Use Claude-specific tools.
<!-- ENDIF -->`;
  fs.writeFileSync(masterPath, dummyRules, "utf-8");

  // 2. Execute the sync script in sandbox using child_process
  try {
    execFileSync(process.execPath, [syncScriptPath], {
      cwd: testDir,
      env: { ...process.env },
      stdio: "pipe"
    });
  } catch (err) {
    // Cleanup first, then fail
    cleanupSandbox(testDir);
    assert.fail(`Execution failed: ${err.message}`);
  }

  // 3. Verify created files
  const expectedFiles = [
    "CLAUDE.md",
    "GEMINI.md",
    ".agents.md",
    ".cursorrules",
    ".clinerules",
    ".windsurfrules"
  ];

  for (const filename of expectedFiles) {
    const filePath = join(testDir, filename);
    assert.ok(fs.existsSync(filePath), `${filename} should be created`);
    const content = fs.readFileSync(filePath, "utf-8");
    assert.ok(content.includes("OMO AGENT RULES: DO NOT EDIT THIS FILE DIRECTLY"), `${filename} should contain warning header`);
    assert.ok(content.includes("Rule 1: Always use clean architecture."), `${filename} should contain common rules`);
    
    if (filename === "CLAUDE.md") {
      assert.ok(content.includes("Rule 3: Use Claude-specific tools."), `${filename} should contain Claude rules`);
      assert.ok(!content.includes("Rule 2: Enforce typescript strict types for Cursor."), `${filename} should NOT contain Cursor rules`);
    } else if (filename === ".cursorrules") {
      assert.ok(content.includes("Rule 2: Enforce typescript strict types for Cursor."), `${filename} should contain Cursor rules`);
      assert.ok(!content.includes("Rule 3: Use Claude-specific tools."), `${filename} should NOT contain Claude rules`);
    }
  }

  // 4. Cleanup
  cleanupSandbox(testDir);
});

function cleanupSandbox(dir) {
  try {
    if (fs.existsSync(dir)) {
      const files = fs.readdirSync(dir);
      for (const file of files) {
        fs.unlinkSync(join(dir, file));
      }
      fs.rmdirSync(dir);
    }
  } catch (e) {
    // ignore
  }
}
